<?php

require_once dirname(__FILE__) . '/../../include/class.Finance.php';
require_once dirname(__FILE__) . '/../../include/initfunctions.php';
require_once dirname(__FILE__) . '/../../include/class.mylog.php';
require_once dirname(__FILE__) . '/../../include/class.Status.php';


$_SESSION = array();
$_SESSION['userid'] = '1';
$_SESSION['username'] = 'unit_test_name';
/**
 * Test class for Finance.
 * Generated by PHPUnit on 2012-02-19 at 23:27:44.
 */
class FinanceTest extends PHPUnit_Framework_TestCase {

  /**
   * @var Finance
   */
  protected $object;
  protected $conn;
  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $db_host = "127.0.0.1";
    $db_user = "db_jenkins_asia";
    $db_pass = "db_jenkins_asia";
    $db_name = "jenkins_asia";
    $this->conn = mysql_connect($db_host,$db_user,$db_pass);
    $this->db_check = mysql_select_db($db_name);
    $this->object = new Finance;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    mysql_close();
  }

  /**
   * @covers Finance::add
   * @todo Implement testAdd().
   */
  public function testAdd() {
    $ret = $this->object->add("test_finance", 1, 100, "USD", 150, "USD");
    $this->assertNotEmpty($ret);
  }

  /**
   * @covers Finance::update
   * @todo Implement testUpdate().
   */
  public function testUpdate() {
    $ret = $this->object->update(1, 200, "RMB", 250, "RMB", 1,1,NULL,1);
    $this->assertTrue($ret);
  }

}

?>
