<?php

require_once dirname(__FILE__) . '/../../include/class.SampleRequest.php';
require_once dirname(__FILE__) . '/../../include/initfunctions.php';
require_once dirname(__FILE__) . '/../../include/class.mylog.php';
require_once dirname(__FILE__) . '/../../include/class.Status.php';


$_SESSION = array();
$_SESSION['userid'] = '1';
$_SESSION['username'] = 'unit_test_name';
/**
 * Test class for SampleRequest.
 * Generated by PHPUnit on 2012-02-21 at 23:00:35.
 */
class SampleRequestTest extends PHPUnit_Framework_TestCase {

  /**
   * @var SampleRequest
   */
  protected $object;
  protected $conn;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new SampleRequest;
    $db_host = "127.0.0.1";
    $db_user = "db_jenkins_asia";
    $db_pass = "db_jenkins_asia";
    $db_name = "jenkins_asia";
    $this->conn = mysql_connect($db_host,$db_user,$db_pass);
    $this->db_check = mysql_select_db($db_name);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    mysql_close();
  }

  /**
   * @covers SampleRequest::add
   * @todo Implement testAdd().
   */
  public function testAdd() {
    $ret = $this->object->add(1, "test comments");
    $this->assertNotEmpty($ret);
  }

  /**
   * @covers SampleRequest::approve
   * @todo Implement testApprove().
   */
  public function testApprove() {
    $ret = $this->object->approve(1,2,'abc');
    $this->assertTrue($ret);
  }

  /**
   * @covers SampleRequest::reject
   * @todo Implement testReject().
   */
  public function testReject() {
    $ret = $this->object->reject(1,3,'dddd');
    $this->assertTrue($ret);
  }

}

?>
