<?php

require_once dirname(__FILE__) . '/../../include/class.Sample.php';
require_once dirname(__FILE__) . '/../../include/initfunctions.php';
require_once dirname(__FILE__) . '/../../include/class.mylog.php';
require_once dirname(__FILE__) . '/../../include/class.Status.php';


$_SESSION = array();
$_SESSION['userid'] = '1';
$_SESSION['username'] = 'unit_test_name';
/**
 * Test class for Sample.
 * Generated by PHPUnit on 2012-02-21 at 19:03:24.
 */
class SampleTest extends PHPUnit_Framework_TestCase {

  /**
   * @var Sample
   */
  protected $object;
  protected $conn;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new Sample;    $db_host = "127.0.0.1";
    $db_user = "db_jenkins_asia";
    $db_pass = "db_jenkins_asia";
    $db_name = "jenkins_asia";
    $this->conn = mysql_connect($db_host,$db_user,$db_pass);
    $this->db_check = mysql_select_db($db_name);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    mysql_close();
  }

  /**
   * @covers Sample::add
   * @todo Implement testAdd().
   */
  public function testAdd() {
    $ret = $this->object->add("test name", 100, 1, 10, "tag_id --1", "test desc");
    $this->assertNotEmpty($ret);
  }

  /**
   * @covers Sample::updateAvailableCount
   * @todo Implement testUpdateAvailableCount().
   */
  public function testUpdateAvailableCount() {
    $ret = $this->object->updateAvailableCount(1, 2);
    $this->assertTrue($ret);
  }

}

?>
